name: Prettier Formatting

on:
  pull_request:
  push:

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run:  |
          cd Code/backend
          npm install

    - name: Run Prettier
      run:  |
        cd Code/backend
        npm run format:fix

    - name: Check code formatting
      run: |
        cd Code/backend
        npm run format
