name: Prettier Formatting

on:
  pull_request:
  push:

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Change Directory to Backend
      run: |
          cd Code/backend

    - name: Install dependencies
      run: npm install

    - name: Run Prettier
      run: npm run format

    - name: Check code formatting
      run: npm run check-format
